In [ ]:
print("Hello world")

Hello world


# Numpy

##Covered Topics
*  1D Arrays
*  Multidimensional Array
*  Flatten
*  Numpy Operation & more






In [5]:
import numpy as np

In [7]:
listpython = [1, 2, 3]
listpython

[1, 2, 3]

In [8]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [9]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [10]:
a + b


array([5, 7, 9])

In [2]:
a * b

array([ 4, 10, 18])

In [3]:
[5] * [6]

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
np.array([5]) * np.array([6])

array([30])

In [11]:
c = np.arange(1, 10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
d = np.arange(1, 10, 0.1)
d

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [13]:
lista = [1, 2, 3]
listb = [5, 6, 7]

lista + listb

[1, 2, 3, 5, 6, 7]

In [14]:
arrayc = np.array(lista + listb)
arrayc

array([1, 2, 3, 5, 6, 7])

In [15]:
e = np.array([1, 2, 3, 4, 5])
sqrte = np.sqrt(e)

In [16]:
e

array([1, 2, 3, 4, 5])

In [17]:
sqrte

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [18]:
e.dtype

dtype('int64')

In [19]:
sqrte.dtype

dtype('float64')

In [20]:
f = np.array([1, 4, 9, 16], float)
f

array([ 1.,  4.,  9., 16.])

In [21]:
g = np.sqrt(f).astype('int32')
g

array([1, 2, 3, 4], dtype=int32)

# 2D Array

In [22]:
h = np.array([[1, 2], [3, 4], [5, 6]])
h

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
h.shape

(3, 2)

In [25]:
i = np.array([[1, 2,3], [4, 5, 6]])
i

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
i.shape

(2, 3)

In [29]:
nprange =  np.arange(1, 10)
nprange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
reshaped = nprange.reshape(3,3)
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
ab = np.arange(1, 11)
ab

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
ab[5]

6

In [35]:
reshaped_out = ab.reshape(5,2)
reshaped_out

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [36]:
reshaped_out[2][1]

6

**Flatten in Numpy**

In [37]:
reshaped.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
reshaped.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])

c1 = np.concatenate((a1,b1))
c1

array([1, 2, 3, 4, 5, 6])

In [43]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
np.zeros_like(reshaped)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
np.zeros_like(reshaped_out)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [47]:
reshaped_out

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Pandas (sneak - peek : D)

In [48]:
import pandas as pd


In [50]:
ourdata = pd.read_csv('/content/Member Details.csv')
ourdata

Name  ID Campus
0  Anjan Das  20    CoU
1  Shahjalal  26    CoU
2      Sajon   5   RUET
3     Tousif   4    CoU

In [51]:
ourdata['Campus']

0     CoU
1     CoU
2    RUET
3     CoU
Name: Campus, dtype: object

In [53]:
ourdata['Campus'].unique()

array(['CoU', 'RUET'], dtype=object)